pipeline:
  identifier: Build_satzisa_java_hello_world_with_maven_1706728281702
  name: Build java-hello-world-with-maven
  orgIdentifier: default
  projectIdentifier: TestProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706727984216
        repoName: satzisa/java-hello-world-with-maven
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      echo <+pipeline.properties.ci.codebase.build.spec.number>
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Maven_Build
                  identifier: Maven_Build
                  spec:
                    shell: Sh
                    command: mvn clean install -gs settings.xml
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - ./**.xml
                    enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: DevDeploy
        identifier: DevDeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: dev1
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev1
          execution:
            steps:
              - step:
                  name: Deploy
                  identifier: Deploy
                  template:
                    templateRef: account.Default_Install_War_Bash
                    versionLabel: v1
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: Rollback
                  timeout: 10m
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                  template:
                    templateRef: account.Default_Install_War_Bash
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
