pipeline:
  identifier: Build_satzisa_java_hello_world_with_maven_1706728281702
  name: Build java-hello-world-with-maven
  orgIdentifier: default
  projectIdentifier: TestProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706727984216
        repoName: satzisa/java-hello-world-with-maven
  stages:
    - stage:
        name: SubProject
        identifier: SubProject
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: helloworldtest
          project: TestProject
          inputs:
            identifier: helloworldtest
            variables:
              - name: TestUser
                type: String
                value: <+input>
          outputs: []
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      echo <+pipeline.properties.ci.codebase.build.spec.number>
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
